name: Publish Composite

on:
  workflow_call:
    secrets:
      OCM_PRIVATE_KEY:
        required: false
      COSIGN_PRIVATE_KEY:
        required: false
      COSIGN_PASSWORD:
        required: false
    inputs:
      image_signing_enabled:
        description: 'Enable image signing (true|false)'
        required: false
        default: false
        type: boolean # Use boolean type
      ocm_signing_enabled:
        description: 'Enable OCM signing (true|false)'
        required: false
        default: false
        type: boolean # Use boolean type

permissions:
  packages: write
  contents: read

jobs:
  push-composite:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token from GitHub App
        id: generate-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42  # v2.1.4
        with:
          app-id: ${{ secrets.APP_PUSH_TAG_ID }}
          private-key: ${{ secrets.APP_PUSH_TAG_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
#          permission-organization-packages: write
          permission-packages: write
          repositories: "components,${{ github.event.repository.name }}"

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Checkout build (taskfiles) repo
        run: |
          git clone --branch main --single-branch https://github.com/openkcm/build.git ./hack/common

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 #v2.0.0
        with:
          version: 3.x
          repo-token: ${{ steps.generate-token.outputs.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.generate-token.outputs.token }}

      - name: Set up Docker Buildx
        timeout-minutes: 5
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          version: latest

      - name: Build & Push Image
        env:
          IMAGE_SIGNING_ENABLED: ${{ inputs.image_signing_enabled }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          OCM_SIGNING_ENABLED: ${{ inputs.ocm_signing_enabled }}
          OCM_PRIVATE_KEY: ${{ secrets.OCM_PRIVATE_KEY }}
          GITHUB_ACTOR: ${{ github.actor }}
          GHCR_PAT: ${{  steps.generate-token.outputs.token }}
        run: |
          task build:apps[composite]:all --verbose
          
      - name: Build and Push OCM Component
        env:
          OCM_PRIVATE_KEY: ${{ secrets.OCM_PRIVATE_KEY }}
          OCM_SIGNING_ENABLED: ${{ inputs.ocm_signing_enabled }}
          GITHUB_ACTOR: ${{ github.actor }}
          GHCR_PAT: ${{  steps.generate-token.outputs.token }}
        run: |
          task build:ocm:all --verbose
